name: Deploy to Production

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build-and-push-ghcr:
    name: Build & Push to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: tekrenewed
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/tekrenewed/ealing-exchange-app:latest
            ghcr.io/tekrenewed/ealing-exchange-app:${{ github.sha }}

  deploy:
    name: Build & Deploy to Firebase
    runs-on: ubuntu-latest
    needs: [build-and-push-ghcr]
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Google Auth
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/286893104325/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-actions-deployer@ealing-exchange-484820.iam.gserviceaccount.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Deploy to Firebase
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting:ealing-exchange --project ealing-exchange-484820
